root: "${outputs_dir}/explainable-earth-embeddings"

satclip_open_clip_vit_h:
  model_path: "${root}/git-10M/txt-open_clip_vit_h__loc-satclip__tproj-linear__lproj-none__tft-lora__lft-only_proj__lora_r-8__loss-clip_symmetric__lr-0.0001__h-4bb7c457/best.pt"

satclip_open_clip_vit_l:
  model_path: "${root}/git-10M/txt-open_clip_vit_l__loc-satclip__tproj-linear__lproj-none__tft-lora__lft-only_proj__lora_r-8__loss-clip_symmetric__lr-0.0001__h-73876bb2/best.pt"

climplicit_open_clip_vit_l:
  model_path: "${root}/git-10M/txt-open_clip_vit_l__loc-climplicit__tproj-linear__lproj-none__tft-lora__lft-only_proj__lora_r-8__loss-clip_symmetric__lr-0.0001__h-a341ad85/best.pt"

geoclip:
  model_path: "${root}/geoclip_init.pt"

csp_fmow_open_clip_vit_l:
  model_path: "${root}/git-10M/txt-open_clip_vit_l__loc-csp_fmow__tproj-linear__lproj-none__tft-lora__lft-only_proj__lora_r-8__loss-clip_symmetric__lr-0.0001__h-86357a7e/best.pt"

