root: "${project_dir}/splice_results"

geoclip_geospatial_all:
  model: "${root}/geoclip/concept_dictionary_n500000/splice_model.pt"
  concepts: "${root}/geoclip/concept_dictionary_n500000/concepts.pt"

geoclip_geoyfcc:
  model: "${root}/geoclip/geoyfcc_concept_set/splice_model.pt"
  concepts: "${root}/geoclip/geoyfcc_concept_set/concepts.pt"

geoclip_test_concepts_1w:
  model: "${root}/geoclip/test_concepts_one_word/splice_model.pt"
  concepts: "${root}/geoclip/test_concepts_one_word/concepts.pt"

satclip_geospatial:
  model: "${root}/txt-open_clip_vit_l__loc-satclip__tproj-linear__lproj-none__tft-lora__lft-only_proj__lora_r-8__loss-clip_symmetric__lr-0.0001__h-73876bb2/augmented_concepts/splice_model.pt"
  concepts: "${root}/txt-open_clip_vit_l__loc-satclip__tproj-linear__lproj-none__tft-lora__lft-only_proj__lora_r-8__loss-clip_symmetric__lr-0.0001__h-73876bb2/augmented_concepts/concepts.pt"

satclip_geospatial_all:
  model: "${root}/txt-open_clip_vit_l__loc-satclip__tproj-linear__lproj-none__tft-lora__lft-only_proj__lora_r-8__loss-clip_symmetric__lr-0.0001__h-73876bb2/concept_dictionary_n500000/splice_model.pt"
  concepts: "${root}/txt-open_clip_vit_l__loc-satclip__tproj-linear__lproj-none__tft-lora__lft-only_proj__lora_r-8__loss-clip_symmetric__lr-0.0001__h-73876bb2/concept_dictionary_n500000/concepts.pt"

satclip_full_git_10m:
  model: "${root}/txt-open_clip_vit_l__loc-satclip__tproj-linear__lproj-none__tft-lora__lft-only_proj__lora_r-8__loss-clip_symmetric__lr-0.0001__h-73876bb2/concept_dictionary/splice_model.pt"
  concepts: "${root}/txt-open_clip_vit_l__loc-satclip__tproj-linear__lproj-none__tft-lora__lft-only_proj__lora_r-8__loss-clip_symmetric__lr-0.0001__h-73876bb2/concept_dictionary/concepts.pt"

satclip_test_concepts_1w:
  model: "${root}/txt-open_clip_vit_l__loc-satclip__tproj-linear__lproj-none__tft-lora__lft-only_proj__lora_r-8__loss-clip_symmetric__lr-0.0001__h-73876bb2/test_concepts_one_word/splice_model.pt"
  concepts: "${root}/txt-open_clip_vit_l__loc-satclip__tproj-linear__lproj-none__tft-lora__lft-only_proj__lora_r-8__loss-clip_symmetric__lr-0.0001__h-73876bb2/test_concepts_one_word/concepts.pt"

climplicit_geospatial_all:
  model: "${root}/txt-open_clip_vit_l__loc-climplicit__tproj-linear__lproj-none__tft-lora__lft-only_proj__lora_r-8__loss-clip_symmetric__lr-0.0001__h-a341ad85/concept_dictionary_n500000/splice_model.pt"
  concepts: "${root}/txt-open_clip_vit_l__loc-climplicit__tproj-linear__lproj-none__tft-lora__lft-only_proj__lora_r-8__loss-clip_symmetric__lr-0.0001__h-a341ad85/concept_dictionary_n500000/concepts.pt"

climplicit_geospatial:
  model: "${root}/txt-open_clip_vit_l__loc-climplicit__tproj-linear__lproj-none__tft-lora__lft-only_proj__lora_r-8__loss-clip_symmetric__lr-0.0001__h-a341ad85/augmented_concepts/splice_model.pt"
  concepts: "${root}/txt-open_clip_vit_l__loc-climplicit__tproj-linear__lproj-none__tft-lora__lft-only_proj__lora_r-8__loss-clip_symmetric__lr-0.0001__h-a341ad85/augmented_concepts/concepts.pt"

climplicit_full_git_10m:
  model: "${root}/txt-open_clip_vit_l__loc-climplicit__tproj-linear__lproj-none__tft-lora__lft-only_proj__lora_r-8__loss-clip_symmetric__lr-0.0001__h-a341ad85/concept_dictionary/splice_model.pt"
  concepts: "${root}/txt-open_clip_vit_l__loc-climplicit__tproj-linear__lproj-none__tft-lora__lft-only_proj__lora_r-8__loss-clip_symmetric__lr-0.0001__h-a341ad85/concept_dictionary/concepts.pt"

climplicit_test_concepts_1w:
  model: "${root}/txt-open_clip_vit_l__loc-climplicit__tproj-linear__lproj-none__tft-lora__lft-only_proj__lora_r-8__loss-clip_symmetric__lr-0.0001__h-a341ad85/test_concepts_one_word/splice_model.pt"
  concepts: "${root}/txt-open_clip_vit_l__loc-climplicit__tproj-linear__lproj-none__tft-lora__lft-only_proj__lora_r-8__loss-clip_symmetric__lr-0.0001__h-a341ad85/test_concepts_one_word/concepts.pt"

csp_fmow_geospatial_all:
  model: "${root}/txt-open_clip_vit_l__loc-csp_fmow__tproj-linear__lproj-none__tft-lora__lft-only_proj__lora_r-8__loss-clip_symmetric__lr-0.0001__h-86357a7e/concept_dictionary_n500000/splice_model.pt"
  concepts: "${root}/txt-open_clip_vit_l__loc-csp_fmow__tproj-linear__lproj-none__tft-lora__lft-only_proj__lora_r-8__loss-clip_symmetric__lr-0.0001__h-86357a7e/concept_dictionary_n500000/concepts.pt"

csp_fmow_geospatial:
  model: "${root}/txt-open_clip_vit_l__loc-csp_fmow__tproj-linear__lproj-none__tft-lora__lft-only_proj__lora_r-8__loss-clip_symmetric__lr-0.0001__h-86357a7e/augmented_concepts/splice_model.pt"
  concepts: "${root}/txt-open_clip_vit_l__loc-csp_fmow__tproj-linear__lproj-none__tft-lora__lft-only_proj__lora_r-8__loss-clip_symmetric__lr-0.0001__h-86357a7e/augmented_concepts/concepts.pt"

csp_fmow_full_git_10m:
  model: "${root}/txt-open_clip_vit_l__loc-csp_fmow__tproj-linear__lproj-none__tft-lora__lft-only_proj__lora_r-8__loss-clip_symmetric__lr-0.0001__h-86357a7e/concept_dictionary/splice_model.pt"
  concepts: "${root}/txt-open_clip_vit_l__loc-csp_fmow__tproj-linear__lproj-none__tft-lora__lft-only_proj__lora_r-8__loss-clip_symmetric__lr-0.0001__h-86357a7e/concept_dictionary/concepts.pt"

csp_fmow_test_concepts_1w:
  model: "${root}/txt-open_clip_vit_l__loc-csp_fmow__tproj-linear__lproj-none__tft-lora__lft-only_proj__lora_r-8__loss-clip_symmetric__lr-0.0001__h-86357a7e/test_concepts_one_word/splice_model.pt"
  concepts: "${root}/txt-open_clip_vit_l__loc-csp_fmow__tproj-linear__lproj-none__tft-lora__lft-only_proj__lora_r-8__loss-clip_symmetric__lr-0.0001__h-86357a7e/test_concepts_one_word/concepts.pt"