checkpoints: /home/libe2152/outputs/explainable-earth-embeddings/skyscript/  # dir of best.pt files (searched recursively) or single .pt file
concepts:    /home/libe2152/projects/eda/0_vocabs/geoyfcc_concept_set.json      # dir of .json files or single .json file
locations:   /home/libe2152/data/s2-100k/index.csv      # parquet/CSV file or directory

num_samples:           20000
stratify_by_continent: true
lat_col: lat
lon_col: lon
