_wandb:
    value:
        cli_version: 0.24.2
        e:
            mq9ol6862tkxhtufe6br65ruk1rytrzi:
                args:
                    - --config
                    - configs/train.yaml
                    - --data.dataset_name
                    - WildSat-Text
                    - --data.data_path
                    - 0_text-descriptions-wildsat/wildsat-dataset-api/output
                    - --data.source_csv_path
                    - 0_text-descriptions-wildsat/wildsat-dataset-api/output/geolocated_text_dataset.csv
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 18
                cpu_count_logical: 36
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "1966736678912"
                        used: "532717285376"
                email: livia.betti@colorado.edu
                executable: /home/libe2152/miniconda3/envs/xai/bin/python
                git:
                    commit: 16065a927d103f1b98603d980adfe707c2c4b110
                    remote: git@github.com:sricke/explainable-earth-embeddings.git
                gpu: Quadro RTX 8000
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 4608
                      memoryTotal: "51539607552"
                      name: Quadro RTX 8000
                      uuid: GPU-8236dd57-7c46-a7f2-0ab9-de764bb4e79e
                    - architecture: Turing
                      cudaCores: 4608
                      memoryTotal: "51539607552"
                      name: Quadro RTX 8000
                      uuid: GPU-eb05d629-0a23-5670-b0e9-e2f8547d227e
                    - architecture: Turing
                      cudaCores: 4608
                      memoryTotal: "51539607552"
                      name: Quadro RTX 8000
                      uuid: GPU-677f4ab1-82ab-7109-6efd-b5323d6fcd45
                    - architecture: Turing
                      cudaCores: 4608
                      memoryTotal: "51539607552"
                      name: Quadro RTX 8000
                      uuid: GPU-8a0ab895-7488-8a5d-70c2-233920980cde
                host: rolfgpu.colorado.edu
                memory:
                    total: "269900156928"
                os: Linux-5.15.0-168-generic-x86_64-with-glibc2.35
                program: /home/libe2152/projects/explainable-earth-embeddings/main.py
                python: CPython 3.12.12
                root: .
                startedAt: "2026-03-16T22:15:44.079927Z"
                writerId: mq9ol6862tkxhtufe6br65ruk1rytrzi
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 63
                - 74
                - 79
                - 80
                - 106
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 63
                - 74
                - 79
                - 80
                - 106
            "3":
                - 7
                - 17
                - 66
            "4": 3.12.12
            "5": 0.24.2
            "6": 5.2.0
            "12": 0.24.2
            "13": linux-x86_64
