# configs/splice.yaml

device: "cuda"
num_samples: 10000      # set to null to use all rows
max_vocab_size: 20000
batch_size: 100
top_k: 10

dataset_csv: "../../data/s2-100k/ee-dataset/dataset.csv"

models:
  - label: "geoclip-geoyfcc"
    ckpt_dir: "~/outputs/explainable-earth-embeddings/geoclip-geoyfcc/checkpoints"
    ckpt_name: "Text2Location-epoch=46-val_loss=1.3700.ckpt"

# Either specify vocab_files explicitly, or leave this commented and keep vocab_dirs
# to have them automatically expanded at load time.
vocab_dirs:
  - "0_vocabs"

l1_penalties: [0.25, 0.15]

known_locations:
  "New York City": [40.7128, -74.0060]
  "Grand Canyon": [36.1069, -112.1129]
  "Rome": [41.9028, 12.4964]
  "Dar es Salaam": [-6.7924, 39.2083]
  "Da Nang": [16.0544, 108.2022]
  "Himilayas": [30.427193, 95.643024]
  "Sahara Desert": [23.4162, 13.4064]

output:
  parquet_dir: "splice_outputs"
  report_dir: "splice_reports"